version: "3.9"

services: # Servicios
  frontend: # Nombre del servicio
    image: node:17-alpine3.12
    command: ["npm", "run", "dev"]
    working_dir: /app
    # volumes:
    #   - myapp:/home/node/app
    volumes:
      - "./app:/app"
    environment:
      PORT: "${PORT}"
    ports:
      - "5000:${PORT}"

volumes: # Volumenes que necesito
  myapp: